// Mock product data for Blush & Bloom website
const products = [
    {
        id: 1,
        name: "Velvet Matte Lipstick - Ruby Rose",
        category: "Makeup",
        subcategory: "Lipsticks",
        price: 899,
        discountPrice: 719,
        rating: 4.8,
        reviews: 234,
        image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop",
        description: "A luxurious matte lipstick that delivers rich color with a smooth, velvety finish. Long-lasting and comfortable wear.",
        shades: ["Ruby Rose", "Coral Crush", "Nude Bliss", "Berry Bomb"],
        ingredients: "Castor Oil, Beeswax, Vitamin E, Mica, Iron Oxides",
        howToUse: "Apply directly to lips. Start from the center and blend outward. For best results, exfoliate lips beforehand."
    },
    {
        id: 2,
        name: "Hydrating Face Serum - Vitamin C",
        category: "Skincare",
        subcategory: "Face Care",
        price: 1299,
        discountPrice: 1039,
        rating: 4.9,
        reviews: 456,
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
        description: "Brightening serum infused with Vitamin C to improve skin tone, reduce dark spots, and provide antioxidant protection.",
        shades: ["Standard"],
        ingredients: "Vitamin C, Hyaluronic Acid, Niacinamide, Aloe Vera Extract",
        howToUse: "Apply 2-3 drops to clean face and neck. Use morning and evening before moisturizer."
    },
    {
        id: 3,
        name: "Silk Foundation - Warm Beige",
        category: "Makeup",
        subcategory: "Foundation",
        price: 1499,
        rating: 4.7,
        reviews: 189,
        image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=400&h=400&fit=crop",
        description: "Buildable medium-coverage foundation with a natural satin finish. Hydrating formula that lasts all day.",
        shades: ["Fair Porcelain", "Warm Beige", "Medium Honey", "Deep Cocoa"],
        ingredients: "Water, Glycerin, Titanium Dioxide, Silica, Vitamin E",
        howToUse: "Apply with fingers, sponge, or brush. Start from center of face and blend outward."
    },
    {
        id: 4,
        name: "Gentle Cleansing Milk",
        category: "Skincare",
        subcategory: "Face Care",
        price: 699,
        discountPrice: 559,
        rating: 4.6,
        reviews: 312,
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
        description: "Creamy cleanser that removes makeup and impurities while maintaining skin's natural moisture balance.",
        shades: ["Standard"],
        ingredients: "Chamomile Extract, Rose Water, Glycerin, Vitamin E",
        howToUse: "Massage onto dry face using circular motions. Rinse with lukewarm water or remove with cotton pad."
    },
    {
        id: 5,
        name: "Luminous Blush - Peach Glow",
        category: "Makeup",
        subcategory: "Blush",
        price: 799,
        rating: 4.8,
        reviews: 278,
        image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&h=400&fit=crop",
        description: "Buildable powder blush with a luminous finish. Adds a natural, healthy glow to cheeks.",
        shades: ["Peach Glow", "Rose Petal", "Coral Sunset", "Nude Charm"],
        ingredients: "Mica, Talc, Zinc Stearate, Vitamin E, Titanium Dioxide",
        howToUse: "Sweep onto cheeks using a blush brush. Build color for desired intensity."
    },
    {
        id: 6,
        name: "Age-Defying Eye Cream",
        category: "Skincare",
        subcategory: "Eye Care",
        price: 1199,
        discountPrice: 959,
        rating: 4.7,
        reviews: 198,
        image: "https://images.unsplash.com/photo-1617897903246-719242758050?w=400&h=400&fit=crop",
        description: "Advanced eye cream that reduces puffiness, dark circles, and fine lines. Peptide-infused formula.",
        shades: ["Standard"],
        ingredients: "Peptides, Caffeine, Vitamin C, Hyaluronic Acid, Retinol",
        howToUse: "Dab a small amount around eye area using ring finger. Use morning and evening."
    },
    {
        id: 7,
        name: "Volumizing Mascara - Black",
        category: "Makeup",
        subcategory: "Mascara",
        price: 599,
        rating: 4.5,
        reviews: 423,
        image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=400&h=400&fit=crop",
        description: "Dramatic volume mascara that separates and defines lashes. Smudge-proof and long-wearing.",
        shades: ["Black", "Brown", "Deep Blue"],
        ingredients: "Beeswax, Carnauba Wax, Vitamin E, Iron Oxides",
        howToUse: "Apply from root to tip. Wiggle wand for maximum volume. Apply second coat for added drama."
    },
    {
        id: 8,
        name: "Moisturizing Body Lotion",
        category: "Skincare",
        subcategory: "Body Care",
        price: 549,
        discountPrice: 439,
        rating: 4.6,
        reviews: 567,
        image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400&h=400&fit=crop",
        description: "Rich body lotion that deeply moisturizes and nourishes skin. Quick-absorbing formula with shea butter.",
        shades: ["Standard"],
        ingredients: "Shea Butter, Coconut Oil, Vitamin E, Aloe Vera",
        howToUse: "Apply to clean skin after shower. Massage in circular motions until absorbed."
    },
    {
        id: 9,
        name: "Liquid Lip Gloss - Crystal Clear",
        category: "Makeup",
        subcategory: "Lip Gloss",
        price: 699,
        rating: 4.4,
        reviews: 234,
        image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop",
        description: "High-shine lip gloss with non-sticky formula. Can be worn alone or over lipstick.",
        shades: ["Crystal Clear", "Rose Shimmer", "Gold Dust", "Plum Glaze"],
        ingredients: "Vitamin E, Jojoba Oil, Mica, Titanium Dioxide",
        howToUse: "Apply to lips using applicator. Layer over lipstick for added shine."
    },
    {
        id: 10,
        name: "Full Coverage Concealer",
        category: "Makeup",
        subcategory: "Concealer",
        price: 899,
        discountPrice: 719,
        rating: 4.7,
        reviews: 345,
        image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=400&h=400&fit=crop",
        description: "Full-coverage concealer that hides imperfections, dark circles, and blemishes. Long-wearing formula.",
        shades: ["Fair", "Light", "Medium", "Tan", "Deep"],
        ingredients: "Water, Glycerin, Titanium Dioxide, Vitamin E",
        howToUse: "Apply to under-eye area and blemishes. Blend with finger or concealer brush."
    },
    {
        id: 11,
        name: "Radiance Eye Shadow Palette",
        category: "Makeup",
        subcategory: "Eyeshadow",
        price: 1599,
        discountPrice: 1279,
        rating: 4.9,
        reviews: 189,
        image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&h=400&fit=crop",
        description: "12-pan eyeshadow palette with matte and shimmer shades. Highly pigmented and blendable.",
        shades: ["Palette"],
        ingredients: "Mica, Talc, Zinc Stearate, Vitamin E, Iron Oxides",
        howToUse: "Apply light shade all over lid. Medium shade to crease. Dark shade to outer corner."
    },
    {
        id: 12,
        name: "Lip Balm - Rose & Hibiscus",
        category: "Skincare",
        subcategory: "Lip Care",
        price: 299,
        rating: 4.5,
        reviews: 678,
        image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400&h=400&fit=crop",
        description: "Nourishing lip balm with rose and hibiscus extract. Protects and moisturizes dry lips.",
        shades: ["Rose & Hibiscus", "Mint Fresh", "Coconut Cream", "Vanilla Bean"],
        ingredients: "Beeswax, Shea Butter, Rose Extract, Vitamin E",
        howToUse: "Apply to lips as needed throughout the day."
    },
    {
        id: 13,
        name: "Sunscreen SPF 50 - Broad Spectrum",
        category: "Skincare",
        subcategory: "Face Care",
        price: 999,
        discountPrice: 799,
        rating: 4.8,
        reviews: 445,
        image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
        description: "Broad-spectrum sunscreen with SPF 50. Lightweight, non-greasy formula that protects against UVA/UVB rays.",
        shades: ["Standard"],
        ingredients: "Zinc Oxide, Titanium Dioxide, Vitamin E, Niacinamide",
        howToUse: "Apply generously 15 minutes before sun exposure. Reapply every 2 hours."
    },
    {
        id: 14,
        name: "Setting Spray - Long Lasting",
        category: "Makeup",
        subcategory: "Setting Spray",
        price: 799,
        rating: 4.6,
        reviews: 234,
        image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?w=400&h=400&fit=crop",
        description: "Makeup setting spray that locks in makeup for up to 16 hours. Refreshing formula with aloe vera.",
        shades: ["Standard"],
        ingredients: "Water, Aloe Vera, Vitamin E, Glycerin",
        howToUse: "Spray evenly over face after makeup application. Hold 8-10 inches away."
    },
    {
        id: 15,
        name: "Night Repair Cream",
        category: "Skincare",
        subcategory: "Face Care",
        price: 1399,
        discountPrice: 1119,
        rating: 4.7,
        reviews: 289,
        image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
        description: "Intensive night cream that repairs and rejuvenates skin while you sleep. Contains retinol and peptides.",
        shades: ["Standard"],
        ingredients: "Retinol, Peptides, Hyaluronic Acid, Vitamin E, Shea Butter",
        howToUse: "Apply to clean face and neck before bed. Use sunscreen during the day."
    },
    {
        id: 16,
        name: "Highlighter - Champagne Glow",
        category: "Makeup",
        subcategory: "Highlighter",
        price: 899,
        rating: 4.8,
        reviews: 312,
        image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&h=400&fit=crop",
        description: "Luminous highlighter that adds a radiant glow to cheekbones, brow bone, and cupid's bow.",
        shades: ["Champagne Glow", "Rose Gold", "Pearl", "Bronze"],
        ingredients: "Mica, Titanium Dioxide, Vitamin E, Iron Oxides",
        howToUse: "Apply to high points of face using brush or finger. Build for desired intensity."
    }
];
